### ISSUE TITLE
IS values differences

### ISSUE THREAD

**Issue by LeonardoLed** [vaquerizaslab/tadtool#18] opened 2019-02-27 22:02 UTC
Hi there, I have a question about of IS values, the problem is that If I get out the IS values from command:
tadtool -v tads it's not same if I get the values from the plot. I attached the values from plot (values_plot) and tads command (values_tads). In theory It should be the same, Do yo know what is the problem?, I use the default window size in both cases.
![plot](https://user-images.githubusercontent.com/33387734/53526099-f91f3700-3aa8-11e9-80af-d5e5746cbb8b.png)
[values_plot.txt](https://github.com/vaquerizaslab/tadtool/files/2912518/values_plot.txt)
[values_tads.txt](https://github.com/vaquerizaslab/tadtool/files/2912519/values_tads.txt)

**Comment by vaquerizaslab-old** [comment] 2019-02-27 22:08
Hi there,

can you please also post both commands you use for tadtool plot and tadtool tads?

Thank you!

**Comment by LeonardoLed** [comment] 2019-02-27 23:47
The command for plot:
_$ tadtool plot exp_15min.matrix chr22.bed chr22:20000000-25000000_

The command using tads command:

_$ tadtool tads -v exp_15min.matrix chr22.bed chr22:20000000-25000000 102353 2 values_tads.txt_

**Comment by kaukrise** [comment] 2019-02-28 08:49
Hello again,

I have pushed a fix for this issue.

This one was a little tough to figure out, because I could not reproduce the issue with another example region. This bug only affects regions with missing values, specifically unmappable regions. Your matrix was showing the discrepancy because there are a lot of those. Essentially, the `plot` command properly masked the missing values, while the `tads` command did not. This should now be fixed.

Thank you for reporting the issue and let me know if you notice anything else!

**Comment by vaquerizaslab-old** [comment] 2019-02-28 08:50
Hello again,

I have pushed a fix for this issue.

This one was a little tough to figure out, because I could not reproduce the issue with another example region. This bug only affects regions with missing values, specifically unmappable regions. Your matrix was showing the discrepancy because there are a lot of those. Essentially, the `plot` command properly masked the missing values, while the `tads` command did not. This should now be fixed.

Thank you for reporting the issue and let me know if you notice anything else!

**Closed as completed by vaquerizaslab-old** 2019-02-28 08:50 UTC

**Comment by vaquerizaslab-old** [comment] 2019-02-28 08:59
I have pushed a new release to Pypi, you can upgrade with

```
pip install --upgrade tadtool
```

Which should install version 0.78.
